---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1mpy7zwlyj3grma7e2jrcxpk77yz7zktnq30k6aa6aghhdz0uwczsy0rejq"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1mpy7zwlyj3grma7e2jrcxpk77yz7zktnq30k6aa6aghhdz0uwczsy0rejq"
